In [7]:
#set：重覆的元素會被移除
set1:set = {1,1,3,5,7,9}
set1.add(11)
set1

#兩個set可以做集合運算(交集、聯集、差集)

#抓set的元素要用forin迴圈
for value in set1:
    print(value)

1
3
5
7
9
11


In [14]:
import numpy as np

array1:np.ndarray = np.array(range(1,10))
print(type(array1))

#陣列運算ndarray
array2 = array1 + 10
print(array2)

<class 'numpy.ndarray'>
[11 12 13 14 15 16 17 18 19]


In [17]:
np.arange(3)
np.arange(1.3 , 3.5 , 0.1)

array([1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4])

In [19]:
np.random.random()

0.9364604154258539

In [22]:
#隨機出10個常態分配
np.random.randn(10)

array([ 0.06037443,  0.14437441,  0.6614287 ,  0.01891653, -0.32712688,
       -0.08660599,  0.11299193, -0.32172633, -0.29203876, -1.17197141])